Makefile
Teaching-projects/SZE-MOSZE-2020-Hello_there pull request #11
Opened 2020-11-03 15:28 UTC by BakiHUN

2020-11-04 16:32 UTC, hegyhati requested changes
Szerintem egy h dependency hianyzik. Azt villamgyorsan hozzatok rendbe (amig a tobbivel vegzem), es akkor beviszem.

A masik, hogy minek a sok sudo? szerintem root user van GHA-nal, vagy tevedek?

2020-11-04 16:32 UTC, hegyhati commented on Makefile
> +player.o: Player.cpp Player.h JsonParser.h
A player nem hasznalja a unitot?

2020-11-04 16:32 UTC, hegyhati commented on Makefile
> +valgrind:
memcheck szebb nev, de ez minor issue.

2020-11-04 16:32 UTC, hegyhati commented on Makefile
> +cppcheck:
ua.

2020-11-04 16:32 UTC, hegyhati commented on Makefile
> +documentation:
ahogy ez sem "doxygen"

2020-11-04 16:32 UTC, hegyhati commented on Makefile
> +documentation:
(es ez a jo, a felreertesek elkerulese vegett)

2020-11-05 16:49 UTC, BakiHUN commented
ha jól értelmeztem a problémát akkor megcsináltam a h dependecy-t

2020-11-06 12:53 UTC, hegyhati approved these changes

2020-11-06 12:53 UTC, hegyhati commented
Nem volt ez annyira villamgyors, de egye fene.

2020-11-06 12:53 UTC, merged