Docker
Teaching-projects/SZE-MOSZE-2020-Hello_there pull request #12
Opened 2020-11-11 12:20 UTC by BakiHUN

2020-11-12 09:29 UTC, hegyhati requested changes
make?!

2020-11-12 15:55 UTC, Holdmedve commented
@hegyhati kész vannak a változtatások

2020-11-23 19:47 UTC, Holdmedve commented
@hegyhati elkészültek a változtatások. bocs, hogy megint tag-ellek, csak szeretnénk a többi feladat úgy csinálni, hogy ez a branch bement.

2020-11-23 19:49 UTC, hegyhati commented
Te jo eg, ezt hogy nem lattam...  sorry. nezem

2020-11-23 19:51 UTC, hegyhati approved these changes
Reszembrol rendben, approve-oltam. amiket irtam, azok igazabol ugy lennenek tenyleg jok, de ha gondoljatok, vigyetek be igy. a merge-et csinaljatok meg nyugodtan, ahogy jonak latjatok.

2020-11-23 19:51 UTC, hegyhati commented on .github/workflows/Workflow.yml
> +        run: make create_test_env
ezt nem vennem kulon, hanem hogyha ez dependency-je monjduk a make unit_test-nek, akkor ugyis megcsinalja.

2020-11-23 19:51 UTC, hegyhati commented on .github/workflows/Workflow.yml
> +        run: make build
ahogy ezt is.

2020-11-23 19:51 UTC, hegyhati commented on Makefile
> +run_unittests:
egyszeruen ide be kell teni dependency-nek a cmake altal keszitett makefile-t.

2020-11-23 20:33 UTC, merged