Feladat 2
Teaching-projects/SZE-MOSZE-2020-Hello_there pull request #2
Opened 2020-09-24 19:20 UTC by Holdmedve

A 2. feladathoz tartozó követelmények úgy gondoljuk, hogy teljesítve. A játék futása során a Unit-ok adatai már json file-okból kerülnek ki, valamint a code tesztelésre kerül minden push esetén egy github action-ön keresztül.

2020-10-01 23:29 UTC, Holdmedve commented
@hegyhati értesítés végett tag-ellek, hátha így megkapod

2020-10-02 13:12 UTC, BakiHUN commented
@hegyhati

2020-10-03 10:40 UTC, hegyhati commented
omg, 9 napig vartal?

2020-10-03 10:45 UTC, hegyhati requested changes
Par aprosag, a json parser elegge bekotott, de azt most majd ugyis meg kell irni szebbre.

2020-10-03 10:45 UTC, hegyhati commented on Unit.cpp
>  void Unit::Defend(const Unit atkUnit)
ne masoljuk le a masik megkapott unit-ot

2020-10-03 10:45 UTC, hegyhati commented on Unit.cpp
> +    //std::cout << atkUnit.GetName() << " -> " << this->GetName() << std::endl;
kodszemetet ne hagyjunk benne

2020-10-03 10:45 UTC, hegyhati commented on Unit.cpp
> +Unit Unit::parseUnit(std::string fileName)
feleslegesen a fajlnevet se masoljuk, az is osszetett adat.

2020-10-03 10:45 UTC, hegyhati commented on good_output.txt
> +Palpatine wins. Remaining HP: 17
Siths ftw.

2020-10-03 10:45 UTC, hegyhati commented on main.cpp
> +        //std::cout << u2.ToString();
kodszermet sehol ne maradjon

2020-10-03 17:24 UTC, Holdmedve commented
@hegyhati elvégeztük a kért változtatásokat

2020-10-05 20:35 UTC, hegyhati approved these changes

2020-10-05 20:35 UTC, hegyhati commented on Unit.cpp
> +	int dmgInflected = atkUnit.GetDmg();
lehetne const, de ez mar tenyleg szorszalhasogatas :-)

2020-10-05 20:35 UTC, hegyhati commented on Unit.cpp
> +Unit Unit::parseUnit(std::string &fileName)
itt viszont illobb colna a const a string-nel, ha referencia

2020-10-05 20:35 UTC, merged