Levelup
Teaching-projects/SZE-MOSZE-2020-Hello_there pull request #5
Opened 2020-10-12 18:15 UTC by Holdmedve

A levelup-pal kapcsolatos követelményekről úgy gondoljuk, hogy teljesítve.

2020-10-13 14:48 UTC, oliverosz requested changes
Nem kellett volna külön workflow-kat csinálni. Egy workflow-ban is lehet több job, amiket párhuzamosan hajt végre. Workflow-ból akkor kell több, ha más esemény triggereli őket. Pl. mást kell csinálni PR nyitásnál meg egy normál push-nál. De nem baj, így is jó.

Amúgy rendben van az SCA és a memcheck. Amit javítani kell a kódban, azt kommentben jeleztem.

2020-10-13 14:48 UTC, oliverosz commented on cppcheck.sh
> +	echo "$(cppcheck *.cpp --enable=style --output-file=style_warnings.txt)"
Az `--enable=style` bekapcsolja a performance warningokat is, úgyhogy kissé redundáns különvenni, de mindegy, maradhat.

2020-10-13 14:48 UTC, oliverosz commented on Player.cpp
> +Player::Player(std::string &name,int hp,int dmg)
`const std::string&`

2020-10-13 14:48 UTC, oliverosz commented on Player.h
> +	void addXp(int number);
Ezek ne legyenek publikusak.

2020-10-13 14:48 UTC, oliverosz commented on Player.h
> +	int getXp() { return xp; };
Ez meg legyen `const`

2020-10-13 14:48 UTC, oliverosz commented on Unit.cpp
> +		dmgInflected += hp;
Jó volt az úgy, hogy a támadót kapja paraméterként, ne lehessen csak úgy tettes nélkül megsebezni.

2020-10-13 14:48 UTC, oliverosz commented on Player.cpp
> +Player::Player(Unit u)
`const Unit&`

2020-10-15 11:52 UTC, BakiHUN commented
Elvégeztük a kért változtatásokat

2020-10-16 17:21 UTC, oliverosz approved these changes

2020-10-16 17:21 UTC, oliverosz commented on Unit.h
> +    int Defend(Unit& );
Lehetett volna const ref, de annyi baj legyen.

2020-10-16 17:22 UTC, oliverosz requested changes
Frissítsétek a branchet a masterre és oldjátok fel a conflictokat.

2020-10-17 15:58 UTC, Holdmedve commented
feloldottuk a merge conflictokat

2020-10-17 16:09 UTC, oliverosz requested changes

2020-10-17 16:09 UTC, oliverosz commented on Player.cpp
> +#include <math.h>
`<cmath>`

2020-10-17 16:09 UTC, oliverosz commented on Unit.cpp
> -			slowerUnitTimer -= slowerUnit->atkCooldown;
Ez így nem jó, ezt nem kellet volna átrakni a mainbe.

2020-10-17 16:09 UTC, oliverosz commented on main.cpp
> +    }
Ez rendben van, de akkor utána már ne legyen használva az u1, u2, mert így átláthatatlan. Bár amúgy is kerüljön vissza a harc vezérlése a Unit osztályba.

2020-10-19 10:59 UTC, BakiHUN commented
Elvégeztük a kért változtatásokat

2020-10-19 15:37 UTC, oliverosz approved these changes

2020-10-19 15:37 UTC, oliverosz commented on Unit.h
> +	static void Fight(Unit& first, Unit& second);
OK... Mondjuk igazán lehetett volna ez is egy egyparaméteres non-static metódus, ami csak a célpontot várja, meg dokumentálva sincs, de most egynek elmegy.

2020-10-19 15:37 UTC, merged